DELETE http://localhost:8080/events/3/register
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE3NjE5OTcwMzcsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInVzZXJJRCI6MX0.h-qObLVvM0-V_3bW0jyVDCSIsvaM1FR2HLGBlqoI-14